### PR TITLE
Integration of  `afragen/git updater lite`

### LINKED ISSUE #240: Plugin should autoupdate
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

To mitigate faulty operation the AU plugin must autoupdate from a known high uptime AspireCloud repository (the one run by AspirePress?). Changes in protocol, emergency  break fix and other "acts of G-d" could require an emergency update and all sites running AU need to quickly update. The Must-Use feature (#136) could also be related to this request.

### Mockups or Images of the feature

none yet, but in theory a mockup could show a notice on dashboard that shows that AU is out of date, maybe support for an emergency banner showing out of date status with a link to update (if auto-update failed somehow).

### LINKED ISSUE #314: [Bug]: AspireUpdate plugin not detected on plugins page
### Contact Details

_No response_

### What happened?

If I search for AspireUpdate, it doesn't detect that it's installed

Image

If I hit install, I get a duplicate plugin in the plugins screen, and it installs to a directory `aspirepress-aspireupdate-9cfc1eb`. 

If I reload the plugins screen, it _still_ doesn't detect that it's installed, though it will fail to install, saying the directory already exists, so that suffix seems to be a hash and not random.  I wonder if this is related in some way to the directory name (aspire-update) not matching the slug (aspireupdate)?

(Also, the "Version" field in the bug report should be updated to 0.6)

### Version

Nightly

### OS

None

### What browsers are you seeing the problem on?

_No response_

### WordPress

_No response_

### PHP

_No response_

### Server

_No response_

### Database

_No response_

### Theme

_No response_

### Must-Use Plugins

_No response_

### Plugins

_No response_

### WordPress Site Health Output (optional)

```shell

```

### Relevant debug log output

```shell

```

### Screenshots/Live demo link

_No response_

### Additional Notes

_No response_

### Code of Conduct

- [x] I agree to follow the Code of Conduct.

### PR DESCRIPTION
**Pull request by afragen**
# Pull Request

Integrate Git Updater Lite

(Please list the changes you made...)

- Add composer require for `afragen/git-updater-lite: ^2`
- Add initialization command to main plugin file
- Added `Updater URI` header to main plugin file but will need to change the `Update URI` header once an AspirePress [Update API Server](https://thefragens.com/update-api-server/) is set up. 

## Did you fix any specific items

Simpler update and integration of AspireUpdate plugin than exists in AC
Fixes #314
Fixes #240 

## CERTIFICATION

By opening this pull request, I do agree to abide by the [Code of Conduct](https://github.com/aspirepress/.github/blob/updating-contributor-policy/CODE_OF_CONDUCT.md) and be bound by the terms of the [Contribution Guidelines](https://github.com/aspirepress/.github/blob/updating-contributor-policy/CONTRIBUTING.md) in effect on the date and time of my contribution as proven by the revision information in GitHub.

### CODE REVIEW

**Comment by afragen** [comment]
PR will fail testing until I commit GUL v2.2.0. Awaiting test updates for it.

**Comment by chuckadams** [comment]
Does this require connection with a GU server instance, or is this just using the GUL routines to process the downloaded zip?  And does fixing the zip fix the issue with non-detection?  I thought that was related to the dash in the dirname.

**Comment by namithj** [comment]
> Does this require connection with a GU server instance, or is this just using the GUL routines to process the downloaded zip? And does fixing the zip fix the issue with non-detection? I thought that was related to the dash in the dirname.

Thats another PR #315

**Comment by afragen** [comment]
It does require a connection with a GU Update API Server instance. 

It will use GUL to update AU.

**Comment by afragen** [comment]
Fixing the workflow is different.

**Comment by afragen** [comment]
The only similar function between GU and GUL is updating and the data for the View details modal. 

GU has so much more and most users won't have it installed, it's a developer tool.

**Comment by afragen** [comment]
FWIW I took out the class GUL_Loader and simply added it for AU.

**Comment by costdev** [comment]
Some info on why this is beneficial:

Currently, AspireUpdate is only available from AspireCloud or direct download. Git Updater Lite decouples updating AspireUpdate from AspireCloud, so that AspireUpdate will receive updates even if the selected server goes down (whether AC production, AC bleeding edge, third-party instance of AC, or third-party API).

Integrating Git Updater Lite means it retrieves the latest update data from the AspirePress website, and pulls it from GitHub. This saves us having to upload a new asset ZIP and maintain update data, which would be required otherwise.

**Comment by namithj** [comment]
Additionally we already spoke about using the GU api which @afragen is developing as another source in AE (which will then reach AU eventually).  Unless a user chooses GU as the plugin source we should not push it upon them.  Let's keep AC and GU separate.

**Comment by costdev** [comment]
> If we ourself are not confident about our update system that we need to fall back on another system, how would we convince others to use AC.

It's not just about confidence. The fundamental purpose of AspireUpdate is to rewrite API urls to another location. That location may not have AspireUpdate in its listings. We therefore need to ensure AspireUpdate is decoupled from the side effect of its own actions.

**Comment by costdev** [comment]
> Additionally we already spoke about using the GU api which @afragen is developing as another source in AE (which will then reach AU eventually). Unless a user chooses GU as the plugin source we should not push it upon them. Let's keep AC and GU separate.

This isn't merging AspireCloud and Git Updater. It's integrating Git Updater Lite and AspireUpdate specifically to handle updating to AspireUpdate from its canonical source because the configured API host may not have any AspireUpdate source available.

While AspirePress would of course like to see everyone using AspireCloud, AspireUpdate, and AspireExplorer in conjunction, there's no requirement to use them with each other. Therefore, what we do in one project shouldn't be assumed to benefit another.

**Comment by namithj** [comment]
We should respect the users decision in that scenario, if we really want to decouple AU from the update process, the functionality should be added to AU core and not as a dependency.  

We should not be introducing third party projects into AU core unless it's mission critical as it will impact security and stability as it's beyond our control.

Dependency decisions like this need to have a triage and then only moved to code phase.

**Comment by costdev** [comment]
> We should respect the users decision in that scenario

"the user's decision" in this scenario may have one of these outcomes:

1. Switched to an API server that doesn't have AspireUpdate available and therefore AspireUpdate can only be updated manually. The user is less likely to know that an update is available, or to manually upgrade.
2. Switched to an API server that may serve its own copy of AspireUpdate, which could have changes in it. This is a supply chain vulnerability.

We don't have control third-party API servers - __that's__ the security and stability issue.

> We should not be introducing third party projects into AU core unless it's mission critical as it will impact security and stability as it's beyond our control.

Of course it's within our control. We choose what we ship with AspireUpdate. If we've tested a newer version of a dependency and it's not stable or secure, we can lock it to the previous version.

**Comment by costdev** [comment]
> This is an Ask.com tool bar like situation where we Trojan horse in another updater.

Also, I'd ask that you take a moment to reconsider before posting this kind of thing. It's needlessly dramatic and taints a discussion by presenting one view as being dishonest or even malicious.

**Comment by namithj** [comment]
> * Switched to an API server that doesn't have AspireUpdate available and therefore AspireUpdate can only be updated manually. The user is less likely to know that an update is available, or to manually upgrade.
> 
> * Switched to an API server that may serve its own copy of AspireUpdate, which could have changes in it. This is a supply chain vulnerability.

Both are valid user decisions and we should respect that.  I really don't understand why we have to bypass everything and auto update one plugin.  AU should be considered as another plugin, it should have no special privileges.

**Comment by costdev** [comment]
> Both are valid user decisions and we should respect that.

A user most likely won't know that their choice doesn't have AspireUpdate or has its own source for AspireUpdate. Their decision was to choose an API host. That doesn't mean the host has informed them, nor that
 the user will have considered that risk.

> I really don't understand why we have to bypass everything and auto update one plugin. AU should be considered as another plugin, it should have no special privileges.

This is no different to using the `UpdateURI` header for what it was designed for, and we're using a dependency that handles all the aspects we'd need to cover instesd of reinventing the wheel. The dependency is written by a trusted member of AspirePress, who has contributed to AspireUpdate, and has 10+ years knowledge the underlying systems, including as a maintainer of the Core component. It's not a case of grabbing a random library.

This doesn't auto-update the plugin unless the user has enabled auto-updates.

File: vendor/afragen/git-updater-lite/Lite.php [hunk 1]
```diff
@@ -0,0 +1,415 @@
...
+		 * Correctly rename dependency for activation.
+		 *
+		 * @param string                           $source        Path fo $source.
+		 * @param string                           $remote_source Path of $remote_source.
+		 * @param \Plugin_Upgrader|\Theme_Upgrader $upgrader      An Upgrader object.
+		 * @param array                            $hook_extra    Array of hook data.
+		 *
+		 * @return string|\WP_Error
+		 */
+		public function upgrader_source_selection( string $source, string $remote_source, \Plugin_Upgrader|\Theme_Upgrader $upgrader, $hook_extra = null ) {
```
Comment (costdev) [inline vendor/afragen/git-updater-lite/Lite.php:173]: It would be great to remove the union typed typehint - I can't see any at the moment - so AspireUpdate can continue to support PHP 7.4 as that accounts for roughly 30% of WP sites for the moment. It's a minimal adjustment, not unlike some of the adjustments we made to dependencies when merging their updates to WP Core, and will be needed less and less in the future as sites move to PHP 8+.

Comment (afragen) [reply vendor/afragen/git-updater-lite/Lite.php]: Made PHP 7.4 compatible in v2.2.0

**Review by costdev — APPROVED** [review]

**Comment by toderash** [comment]
Just to complete the loop here for documentation, this was decided in our weekly PM meeting after reviewing all the concerns and the proposed PR. The approach of updating AspireUpdate from GitHub rather than from AspireCloud closes a potential security issue in the supply chain. This doesn't need documenting here, but there are specific reasons to handle this outside of ACloud, and the concerns expressed have been identified and addressed accordingly. cc @costdev
