### PR TITLE
API_Rewrite: Return `WP_Error` object for non-200 responses.

### LINKED ISSUE #294: [Bug]: Error handling issues with Plugin Install page
_Note: sorry about the confused report: I **did** get a raft of deprecations on the settings page once, and I got those confused with these errors.  I'll open a new report about the deprecations after I disable opcache so I can see them._

### Contact Details

_No response_

### What happened?

I entered a bad API key (pasted the url into the wrong field) and got a 401 error when hitting the AC backend (on .io):

```
Warning: Undefined property: stdClass::$plugins in /app/web/wp/wp-admin/includes/class-wp-plugin-install-list-table.php on line 249 
Warning: Undefined property: stdClass::$info in /app/web/wp/wp-admin/includes/class-wp-plugin-install-list-table.php on line 257 
Warning: Trying to access array offset on null in /app/web/wp/wp-admin/includes/class-wp-plugin-install-list-table.php on line 257 
```

And one in the main UI section:

```
Deprecated: number_format(): Passing null to parameter #1 ($num) of type float is deprecated in /app/web/wp/wp-includes/functions.php on line 424
```

### Version

Nightly

### OS

None

### What browsers are you seeing the problem on?

_No response_

### WordPress

_No response_

### PHP

_No response_

### Server

_No response_

### Database

_No response_

### Theme

_No response_

### Must-Use Plugins

_No response_

### Plugins

_No response_

### WordPress Site Health Output (optional)

```shell

```

### Relevant debug log output

```shell

```

### Screenshots/Live demo link

_No response_

### Additional Notes

_No response_

### Code of Conduct

- [x] I agree to follow the Code of Conduct.

### PR DESCRIPTION
**Pull request by costdev**
# Pull Request

## What changed?

- A `WP_Error` object is returned when the request performed by `API_Rewrite::pre_http_request()` returns a non-200 HTTP response.
- A PHPUnit test has been added to verify and protect this behaviour going forward.

## Why did it change?

When the API request failed, the failed response was passed to admin pages, causing PHP warnings. This handles the errors as they should be handled.

## Did you fix any specific issues?

Fixes #294 

## CERTIFICATION

By opening this pull request, I do agree to abide by the [Code of Conduct](https://github.com/aspirepress/.github/blob/updating-contributor-policy/CODE_OF_CONDUCT.md) and be bound by the terms of the [Contribution Guidelines](https://github.com/aspirepress/.github/blob/updating-contributor-policy/CONTRIBUTING.md) in effect on the date and time of my contribution as proven by the revision information in GitHub.

### CODE REVIEW

File: includes/class-api-rewrite.php [hunk 1]
```diff
@@ -150,6 +150,13 @@ public function pre_http_request( $response, $parsed_args, $url ) {
 
 					Debug::log_response( $response );
 
+					if ( 200 !== wp_remote_retrieve_response_code( $response ) ) {
+						return new \WP_Error(
+							'failed_request',
+							wp_remote_retrieve_response_message( $response )
+						);
+					}
+
```
Comment (namithj) [inline includes/class-api-rewrite.php:159]: We should add this event to Debug log (string) too so that it can be tracked

**Review by namithj — CHANGES_REQUESTED** [review]

File: includes/class-api-rewrite.php (hunk 1 above)
Comment (costdev) [reply includes/class-api-rewrite.php:158]: Added in [5953646](https://github.com/aspirepress/aspireupdate/pull/300/commits/5953646f5d3e66997f3da7b39d72e13adf106669).

Comment (namithj) [reply includes/class-api-rewrite.php:158]: May be "Request Failed :", The Message by itself wont give the context without the prefix

Comment (costdev) [reply includes/class-api-rewrite.php:164]: Added in [8725cf4](https://github.com/aspirepress/aspireupdate/pull/300/commits/8725cf45e5082f9e1c3fd9df6c3ae6a00d33e2d0).

**Review by namithj — APPROVED** [review]
